project:
  type: book
  output-dir: docs



book:
  title: "Data Science II with python (Class notes)"
  subtitle: "STAT 303-2-Sec20"
  date: "1/2/2026"
  author: "Lizhen Shi"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - Lec1_SimpleLinearRegression.ipynb
    - Lec2_MultipleLinearRegression.ipynb
    - Lec3_VariableTransformations_and_Interactions.ipynb
    - polynominal_features.ipynb
    - potential_issue_3.ipynb
    - Lec5_Potential_issues.ipynb
    - Logistic Regression.ipynb
    - Logistic Regression - Decision Boundary and Feature Engineering (Nonlinear Features).ipynb
    - cross_validation.ipynb
    - Regularization in Python.ipynb
    - Feature Selection.ipynb
  
    
   
  appendices: 
    - Assignment_1.ipynb
    - Assignment_2.ipynb
    #- Assignment 3.ipynb
    #- Assignment_4.ipynb
    #- Assignment5.ipynb
    - Datasets.ipynb
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt